### ISSUE TITLE
Allow Terrajet-based providers to run in shared gRPC mode

### ISSUE THREAD

**Issue by ulucinar** [crossplane/terrajet#261]
### What problem are you facing?

We would like to have an option to prevent the Terraform CLI from forking the native provider plugin for each request, and instead communicate with a long running provider process via gRPC in the context of #38 and #233.

### How could Terrajet help solve your problem?

We can extent `provider-jet-template` and probably the configuration framework in Terrajet with options for configuring Terrajet-based providers to use a shared gRPC server.

**Comment by muvaf** [comment]
One implication of this is that we should warn against [using env vars](https://github.com/crossplane/terrajet/blob/1dfbdfcd7162105a67bd7ffb53b689f46a150450/pkg/terraform/store.go#L56) for authentication because TF won't fork the provider process anymore, hence it cannot affect its env vars. Having it there as available will be confusing if we have the shared provider in the template as the default mode of execution. In fact, I think we can deprecate it and then remove in a future release in order to push for standardization of the execution mode to shared provider.
