### ISSUE TITLE
Fix security vulnerabilities with hashicorp/go-getter upgrade to v1.6.1

### ISSUE THREAD

**Issue by nimish22** [crossplane/terrajet#294]
### What happened?

Security vulnerability scanners like Twistlock and Snyk are reporting security issues introduced by _hashicorp/go-getter_ on images built using Terrajet. These security vulnerabilities are classified as critical and preventing us from using the built images. The CVEs are:

[CVE-2022-30322](https://nvd.nist.gov/vuln/detail/CVE-2022-30322)
[CVE-2022-30321](https://nvd.nist.gov/vuln/detail/CVE-2022-30321)
[CVE-2022-26945](https://nvd.nist.gov/vuln/detail/CVE-2022-26945)
[CVE-2022-30323](https://nvd.nist.gov/vuln/detail/CVE-2022-30323)

### How can we reproduce it?

Point the [Snyk](https://app.snyk.io/login?cta=html-button-click&loc=page-body&page=homepage) to the Git repository to run scurity scan (eg: https://github.com/crossplane-contrib/provider-jet-datadog, https://github.com/crossplane/terrajet). The report points out the security vulnerabilities.

### Potential fix?
These CVEs can be resolved by using the _hashicorp/go-getter_ v1.6.1 or 2.1.0.

**Comment by muvaf** [comment]
It seems that we have that dependency because of v1 of terraform-plugin-sdk but that's already declared as end-of-life [here](https://github.com/hashicorp/terraform-plugin-sdk/blob/v1-maint/SUPPORT.md). We're only using that dependency to make it possible to work with v1-based providers by converting their schema to v2 [here](https://github.com/crossplane/terrajet/blob/main/pkg/types/conversion/sdkv1/sdkv1.go#L30) but we may remove it altogether. @turkenh what are your thoughts?
